### ISSUE TITLE
Howcome OpenTRV is dead?

### ISSUE THREAD

**Issue by Ryton** [opentrv/opentrv-dead#1]
Hey,

Is this project superceided by another one, 
or do you have other priorities atm?

If it exists, I could not find its successor... Could you point me towards it?

**Comment by brunogirin** [comment]
Hi,

OpenTRV is very much alive. However, a lot of the code currently lives in a different repository: https://github.com/DamonHD/OpenTRV. We will move to this one once we have a bit of spare time to re-arrange and clean the repo.

**Comment by Ryton** [comment]
Ah, thanks for this resassuring message! 
I was scared for a while, as I didn't notice much activity on the [main site](http://opentrv.org.uk/), apart from the last newsflash around june 2015 (rev6).
